dist: trusty
sudo: required
  
before_install:
   - cd $HOME
   - git clone --recursive https://github.com/noseglasses/Kaleidoscope-Testing.git
   - Kaleidoscope-Testing/travis/before_install.sh

script: skip
    
jobs:
  include:
    - stage: test
      script:
         - cd $HOME
         - mkdir ktest
         - cd ktest
         - $HOME/Kaleidoscope-Testing/travis/test_kaleidoscope_module.sh 'https://github.com/noseglasses/Kaleidoscope-Papageno.git'
         
notifications:
  email:
    recipients:
      - shinynoseglasses@gmail.com
    on_failure: always
    
cache:
ccache: true
