dist: trusty
sudo: false
os:
  - linux
install:
  - git clone --depth 1 --recurse-submodules https://github.com/keyboardio/Arduino-Boards hardware/keyboardio/avr
  - git clone https://github.com/noseglasses/Model01-Firmware-Papageno-Test.git Model01-Firmware
  - git clone https://github.com/noseglasses/Kaleidoscope_Papageno.git keyboardio/Arduino-Boards hardware/keyboardio/avr/libraries/Kaleidoscope_Papageno
script:
  - make travis-test BOARD_HARDWARE_PATH=$(pwd)/hardware
notifications:
  email:
    recipients:
      - shinynoseglasses@gmail.com
    on_failure: always
cache:
  ccache: true
